### ISSUE TITLE
Features / VS Code

### ISSUE THREAD

**Issue by fulldecent** [JeroenDeDauw/new-php-project#11]
For features, please specify if projects using this template will be usable out of the box with VS Code for testing. Or if an extension is required, please explain that.

**Comment by JeroenDeDauw** [comment]
I do not know VS Code. Please see the README for installation and usage instructions.

**Comment by fulldecent** [comment]
The `make` command is what I was looking for I'll use that. Thank you. It looks like you do NOT get inline errors shown in the editor while you're editing. But that's okay.
